//export const API_BASE_URL = 'http://localhost:8080';
export const API_BASE_URL = 'https://clinina-backend-2.onrender.com';


export const racasDeCachorro: string[] = [
  "S.R.D",
  "Affenpinscher",
  "Afegão Hound",
  "Airedale Terrier",
  "Akita",
  "Akita Americano",
  "American Staffordshire Terrier",
  "Barbet",
  "Basenji",
  "Basset Artesiano Normando",
  "Basset Fulvo da Bretanha",
  "Basset Hound",
  "Beagle",
  "Beagle Harrier",
  "Bearded Collie",
  "Bedlington Terrier",
  "Bichon Bolonhês",
  "Bichon Frisé",
  "Bichon Havanês",
  "Bichon Maltês",
  "Biewer Terrier",
  "Billy",
  "Black and Tan Coonhound",
  "Bloodhound",
  "Bobtail",
  "Boiadeiro Australiano",
  "Boiadeiro Bernês",
  "Boiadeiro de Appenzell",
  "Boiadeiro de Entlebuch",
  "Boiadeiro de Flandres",
  "Border Collie",
  "Border Terrier",
  "Borzoi",
  "Boston Terrier",
  "Boxer",
  "Buldogue Campeiro",
  "Buldogue Francês",
  "Buldogue Inglês",
  "Bull Terrier",
  "Bulmastife",
  "Cairn Terrier",
  "Cane Corso",
  "Cão de Água Espanhol",
  "Cão de Crista Chinês",
  "Cão de Fila de São Miguel",
  "Cão de Montanha dos Pirenéus",
  "Cão de Santo Humberto",
  "Cão dos Pirinéus",
  "Cão Lobo Checoslovaco",
  "Cão Pelado do Peru",
  "Cão Pelado Mexicano",
  "Cão Pastor de Brie",
  "Cavalier King Charles Spaniel",
  "Chesapeake Bay Retriever",
  "Chihuahua",
  "Chow Chow",
  "Cocker Spaniel Americano",
  "Cocker Spaniel Inglês",
  "Collie",
  "Coton de Tulear",
  "Dachshund",
  "Dálmata",
  "Dandie Dinmont Terrier",
  "Doberman",
  "Dogo Argentino",
  "Dogue Alemão",
  "Dogue de Bordeaux",
  "Elkhound Norueguês",
  "Epagneul Breton",
  "Epagneul Francês",
  "Epagneul Picard",
  "Fox Terrier",
  "Galgo Espanhol",
  "Galgo Irlandês",
  "Golden Retriever",
  "Grande Boiadeiro Suiço",
  "Greyhound",
  "Grifo da Bélgica",
  "Husky Siberiano",
  "Jack Russell Terrier",
  "Labrador Retriever",
  "Lhasa Apso",
  "Malamute do Alasca",
  "Maltês",
  "Mastife",
  "Mastim Napolitano",
  "Mastim Tibetano",
  "Norfolk Terrier",
  "Norwich Terrier",
  "Papillon",
  "Pastor Alemão",
  "Pastor Australiano",
  "Pastor Belga",
  "Pastor de Shetland",
  "Pastor Maremano Abruzês",
  "Pequinês",
  "Perdigueiro Português",
  "Pinscher",
  "Pit Bull Terrier",
  "Pointer",
  "Poodle",
  "Pug",
  "Retriever do Labrador",
  "Rottweiler",
  "Samoieda",
  "São Bernardo",
  "Schipperke",
  "Schnauzer",
  "Setter Irlandês",
  "Shiba Inu",
  "Shih Tzu",
  "Silky Terrier",
  "Skye Terrier",
  "Spitz Alemão",
  "Spitz Finlandês",
  "Staffordshire Bull Terrier",
  "Terra Nova",
  "Terrier Brasileiro",
  "Terrier Escocês",
  "Terrier Irlandês",
  "Terrier Tibetano",
  "Vizsla",
  "Weimaraner",
  "Welsh Corgi",
  "West Highland White Terrier",
  "Whippet",
  "Yorkshire Terrier"
];

export const racasDeGato: string[] = [
  "S.R.D",
  "Persa",
  "Siamês",
  "Maine Coon",
  "Sphynx",
  "Bengal",
  "Ragdoll",
  "British Shorthair",
  "Scottish Fold",
  "Abissínio",
  "Norueguês da Floresta",
  "American Shorthair",
  "Birmanês",
  "Savannah",
  "Exotic Shorthair",
  "Oriental",
  "Himalaio",
  "Chartreux",
  "Russian Blue",
  "Devon Rex",
  "Cornish Rex",
  "Turkish Angora",
  "Manx",
  "Selkirk Rex",
  "Bombay",
  "Tonquinês",
  "Burmilla",
  "Ocicat",
  "Singapura",
  "Peterbald",
  "LaPerm",
  "Nebelung",
  "Munchkin",
  "Toyger",
  "Balines",
  "Cymric",
  "Korat",
  "Somali",
  "Japanese Bobtail",
  "Turkish Van"
];

export const listaDeEstados: string[] = [
  'AC', 'AL', 'AP', 'AM', 'BA', 'CE', 'DF', 'ES', 'GO', 'MA', 'MG', 'MS',
  'MT', 'PA', 'PB', 'PE', 'PI', 'PR', 'RJ', 'RN', 'RO', 'RR', 'RS', 'SC',
  'SE', 'SP', 'TO'
];
